Imports MySql.Data.MySqlClient
Imports iTextSharp.text
Imports iTextSharp.text.pdf
Imports System.IO
Imports System.Diagnostics

Public Class Form3
    Dim connString As String = "server=localhost;database=Scoopify_Creamery;user=root;password=BugfixMaster#22;"

    Private Sub Form3_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        LoadInventory()
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        LoadInventory()
    End Sub

    Private Sub LoadInventory()
        Using conn As New MySqlConnection(connString)
            conn.Open()
            Dim query As String = "SELECT item_name, category, current_stock, reorder_level, status FROM inventory ORDER BY category, item_name"
            Dim adapter As New MySqlDataAdapter(query, conn)
            Dim table As New DataTable()
            adapter.Fill(table)
            DataGridView1.DataSource = table
        End Using
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Dim inventoryForm As New Form3()
        inventoryForm.Show()
    End Sub

    Private Sub DataGridView1_CellContentClick(sender As Object, e As DataGridViewCellEventArgs) Handles DataGridView1.CellContentClick

    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click

        Try

            Dim folderPath As String =
            Path.Combine(Application.StartupPath, "Reports")

            If Not Directory.Exists(folderPath) Then
                Directory.CreateDirectory(folderPath)
            End If

            Dim filePath As String =
            Path.Combine(folderPath,
            "Inventory_Report_" &
            DateTime.Now.ToString("yyyyMMdd_HHmmss") &
            ".pdf")

            Dim doc As New Document(PageSize.A4, 30, 30, 30, 30)

            PdfWriter.GetInstance(doc,
                              New FileStream(filePath,
                                             FileMode.Create))

            doc.Open()

            'Title

            Dim titleFont As Font =
            FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 22)

            Dim headerFont As Font =
            FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12)

            Dim normalFont As Font =
            FontFactory.GetFont(FontFactory.HELVETICA, 11)

            Dim title As New Paragraph(
            "🍦 SCOOPIFY CREAMERY 🍦",
            titleFont)

            title.Alignment = Element.ALIGN_CENTER

            doc.Add(title)

            Dim subtitle As New Paragraph(
            "Inventory Report",
            headerFont)

            subtitle.Alignment = Element.ALIGN_CENTER

            doc.Add(subtitle)

            doc.Add(New Paragraph(
            "Generated on: " &
            DateTime.Now.ToString(
            "MMMM dd, yyyy hh:mm tt"),
            normalFont))

            doc.Add(New Paragraph(" "))

            'Table

            Dim pdfTable As New PdfPTable(5)

            pdfTable.WidthPercentage = 100

            pdfTable.SetWidths(
            {3, 2, 2, 2, 2})

            pdfTable.AddCell("Item Name")
            pdfTable.AddCell("Category")
            pdfTable.AddCell("Stock")
            pdfTable.AddCell("Reorder Level")
            pdfTable.AddCell("Status")

            For Each row As DataGridViewRow In DataGridView1.Rows

                If Not row.IsNewRow Then

                    pdfTable.AddCell(
                    row.Cells("item_name").Value.ToString())

                    pdfTable.AddCell(
                    row.Cells("category").Value.ToString())

                    pdfTable.AddCell(
                    row.Cells("current_stock").Value.ToString())

                    pdfTable.AddCell(
                    row.Cells("reorder_level").Value.ToString())

                    pdfTable.AddCell(
                    row.Cells("status").Value.ToString())

                End If

            Next

            doc.Add(pdfTable)

            doc.Add(New Paragraph(" "))
            doc.Add(New Paragraph(
            "Total Inventory Items: " &
            (DataGridView1.Rows.Count - 1),
            normalFont))

            doc.Add(New Paragraph(" "))
            doc.Add(New Paragraph(
            "Generated by Scoopify Inventory Management System",
            normalFont))

            doc.Close()

            MessageBox.Show(
            "Inventory report generated successfully!",
            "Success",
            MessageBoxButtons.OK,
            MessageBoxIcon.Information)

            Process.Start("explorer.exe", folderPath)

        Catch ex As Exception

            MessageBox.Show(ex.Message)

        End Try

    End Sub
End Class